/** Request DTOs — M01 `auth` (CONTRACTS.md §4.1). Validated by the global `ValidationPipe` (`main.ts`). */
import { IsOptional, IsString, IsUUID, Length, Matches, MinLength } from 'class-validator';

export class LoginDto {
  @IsString()
  @MinLength(1)
  username!: string;

  @IsString()
  @MinLength(1)
  password!: string;

  @IsOptional()
  @IsUUID()
  deviceId?: string;
}

export class RefreshDto {
  @IsString()
  @MinLength(1)
  refreshToken!: string;
}

export class LogoutDto {
  @IsString()
  @MinLength(1)
  refreshToken!: string;
}

export class SetPinDto {
  @IsString()
  @MinLength(1)
  currentPassword!: string;

  @IsString()
  @Length(6, 6)
  @Matches(/^\d{6}$/, { message: 'pin must be exactly 6 digits' })
  pin!: string;
}

/**
 * `VerifyPinDto` used to live here, for `POST /auth/pin/verify` — deleted with
 * that endpoint (B-15). Its `context: 'pos_override' | 'approval'` is now
 * expressed by WHICH document a one-time code is bound to, which is stronger:
 * a context string was a label, a `document_id` is a constraint.
 */

/**
 * B-17 — `POST /api/auth/offline-credential/:credentialId/unlock-code`.
 *
 * The `challenge` is generated BY THE TABLET when it locks a credential, and
 * read to head office over the phone. It is not a secret and carries no
 * authority on its own; it is here so the code that comes back is inert against
 * any other lock, on any other device, at any other time.
 */
export class OfflineUnlockCodeDto {
  @IsString()
  @Matches(/^\d{6}$/, { message: 'challenge must be exactly 6 digits' })
  challenge!: string;
}

export class OfflineCredentialRefreshDto {
  @IsUUID()
  deviceId!: string;
}

export class RevokeCredentialDto {
  @IsString()
  @MinLength(1)
  reason!: string;
}
